### PR TITLE
11.0 mig ddmrp product replace

### PR DESCRIPTION
**Pull request by grindtildeath**
Depends on :
 - [ ] #47 

Todo :
 - [x] Add tests

### CODE REVIEW

**Comment by grindtildeath** [comment]
@lreficent @jbeficent I just added a test where I'm not sure if the result is correct as I'm missing context.

I used the 'Copy put away strategy' feature, and when checking if the new product has the same putaway strategy than the old product, it appears the putaway strategy was moved (instead of copied) from old product to new product.
Is this correct or should we ensure a copy is done (instead of move) ?

**Comment by LoisRForgeFlow** [comment]
@grindtildeath nice catch, It's better if the put away strategy is copied to the new product.

**Comment by grindtildeath** [comment]
@lreficent Thanks for your answer. I suppose we can now remove work in progress and wait reviews :)

**Comment by LoisRForgeFlow** [comment]
@grindtildeath Really appreciate the migration but we still need to merge a lot of dependencies for ddmrp, ddmrp itself and then this, so I fear this will have to wait for some time :sweat_smile:

**Review by simahawk — CHANGES_REQUESTED** [review]
code from #47 should be excluded and included via oca_dependencies.txt
Quick code review: sounds good.

**Comment by LoisRForgeFlow** [comment]
This is weird, I cannot fin this branch in you repo @grindtildeath https://github.com/grindtildeath/ddmrp/branches

**Comment by grindtildeath** [comment]
@lreficent That happens because grindtildeath/ddmrp is a fork of OCA/ddmrp as I did fork OCA's before Eficent's. The branch you're looking for is on grindtildeath/ddmrp-1 : https://github.com/grindtildeath/ddmrp-1/tree/11.0-mig-ddmrp_product_replace
:wink:

**Comment by LoisRForgeFlow** [comment]
@grindtildeath that's right, thanks!

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM, thanks for the migration!

**Pull request merged**
