### PR TITLE
[11.0][IMP] ddmrp: more robust buffer status computation on PO lines.

### PR DESCRIPTION
**Pull request by max3903**
Supersedes #63 

CC: @lreficent @jbeficent @jgrandguillaume

### CODE REVIEW

**Comment by jgrandguillaume** [comment]
@lreficent Can you please relaunch Travis ? We're kind of block because of the red Travis flag..

**Review by jgrandguillaume — APPROVED** [review]
LGTM

**Comment by LoisRForgeFlow** [comment]
Thanks guys! Just let me inform you with our "merging order" as to say:

1. https://github.com/mpanarin/manufacture/pull/1 will make work 2.
2. https://github.com/OCA/manufacture/pull/254
3. https://github.com/Eficent/ddmrp/pull/64
4. This (I see the lint issues present in 3. are fixed here, thanks again).
5. extra changes still not opened as PR but almost ready.
6. hopefully Move to OCA finally?

If we don't get an answer on PR 1 by the beggining of next week I plan to supersede PR 2 with a new PR to try to move forward

**Review by LoisRForgeFlow — APPROVED** [review]
Green!

**Pull request merged**
