### PR TITLE
[IMP] Add buffer profiles

### PR DESCRIPTION
**Pull request by max3903**

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@max3903 Can the data loaded using CSV be translated afterwards?

**Comment by max3903** [comment]
@jbeficent Whether a value can be translated or not depends on the field definition, not the value. Which fields do you want to translate? All fields in the CSV are selection or relations.

**Comment by JordiBForgeFlow** [comment]
Why do you close it?

**Comment by JordiBForgeFlow** [comment]
Oh got it

**Pull request closed without merging**
