### PR TITLE
[11.0]Fix tests

### PR DESCRIPTION
**Pull request by StephanRozendaal**
Get the tests running again for version 11.0

TODO: mrp_bom_location module has not been ported to 11.0 yet, I merged a WIP version to get the tests working.

### CODE REVIEW

**Comment by StephanRozendaal** [comment]
Problem installing bokeh dependency.
It need Tornado >= 4.3, but pip will default to 5.0.2 which probably needs a newer Python(2.7.9) version.
Seems like you're running this on Ubuntu trusty, which uses 2.7.6.

I see two paths we can try:
 - update requirements.txt of web module to use tornado=4.3
 - update the python version, this might need a newer OS

**Comment by StephanRozendaal** [comment]
bokeh dependency is resolved, we swiched to Python 3.5

**Review by LoisRForgeFlow — APPROVED** [review]
Tests added makes sense and pass, travis is red due to pylint error (I'll merge and fix it later).

Thanks a lot @StephanRozendaal :smile:

**Comment by StephanRozendaal** [comment]
@lreficent: You're welcome!

I don't think this should be merged directly though, there is still a reference to my own manufacture repo for merge-bom-location module.

**Comment by LoisRForgeFlow** [comment]
@StephanRozendaal ugh, that's right, always that dependency... I'm going to try to fix that.

**Comment by LoisRForgeFlow** [comment]
@StephanRozendaal `mrp_bom_location` is finally merged at OCA/manufacture :tada: Could you please update oca_dependencies here?

**Comment by StephanRozendaal** [comment]
@lreficent Nice! I updated the oca_dependencies and changed the name of this PR since it's no longer WIP.

**Comment by LoisRForgeFlow** [comment]
Thanks!

**Pull request merged**
